[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=2

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_cvn_068
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=cvn-68
AircraftEmblemTexture=cvn-68
ResourcesLiveryFolder=ships/usn_cvn_nimitz/
LiveryTexture=usn_cvn_nimitz_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983
CustomAirGroup=True
usn_f-14a=Squadron5,10|Squadron7,10
usn_a-7e=Squadron7,11|Squadron8,11
usn_a-6e=Squadron2,11
usn_e-2c=Squadron6,4
usn_ea-6b=Squadron8,4
usn_ra-5c=Squadron6,4
usn_s-3a=Squadron1,10
usn_sh-3h=Squadron1,8


[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_cvn_069
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=cvn-69
AircraftEmblemTexture=cvn-69
ResourcesLiveryFolder=ships/usn_cvn_nimitz/
LiveryTexture=usn_cvn_nimitz_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1987
CustomAirGroup=True
usn_f-14a=Squadron11,11|Squadron12,10
usn_a-7e=Squadron1,9|Squadron5,9
usn_a-6e=Squadron4,10
usn_e-2c=Squadron4,4
usn_ea-6b=Squadron4,4
usn_s-3a=Squadron4,10
usn_sh-3h=Squadron1,8

#[Variant3]  #Not included atm
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_cvn_070
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=cvn-70
#AircraftEmblemTexture=cv-70
#ResourcesLiveryFolder=ships/usn_cvn_nimitz/
#LiveryTexture=usn_cvn_nimitz_tx
#ResourcesFlagFolder=ships/materials/textures/
#FlagTexture=flag_us
#Nation=US
#ServiceDate=1982
#CustomAirGroup=True
#usn_f-14a=Squadron13,11|Squadron2,10
#usn_a-7e=Default,11|Default,9
#usn_a-6e=Squadron6,10
#usn_e-2c=Squadron1,4
#usn_ea-6b=Squadron5,4
#usn_s-3a=Squadron8,10
#usn_ra-5c=Default,3