[General]
# GBU-15(V)2/B IIR
Type=Bomb                              // can be Projectile, Missile, RBU, ASROC, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
IsInterceptable=True                   // for bombs only, if False, bomb cannot be fired upon, default is false

Mass=1130                              // in kg. Used for aircraft
AmmoPoints=1695                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard                    // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=6  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types: 0 = Impact Fuze, 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=62
ImpactSize=VeryLarge                // Impact size, can be small, medium, large, verylarge
Penetration=Heavy              // can be minor, moderate, heavy, always

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=1
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=2.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
GravityFactor=2
TerminalApproachDist=1000              // in N. miles. At this distance seeker will be turned on.
SupportsBanking=True                   // if the missile will bank when turning
#========================================= Launch stats ============================================================
MaxTurnRate=4                          // Maximum turnrate in degrees per second
MinLaunchRange=3                       // Minimum launch range in nautical miles
MaxLaunchRange=15                      // Maximum launch range in nautical miles
MinLaunchAltitude=500                  // Minimum launch altitude in feet.
MaxLaunchAltitude=60000                // Maximum launch altitude in feet.
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
VerticalWobblingStrength=8.0           // amplitude of wobbling
VerticalWobblingSpeed=3.0              // frequency of wobbling
#========================================     Seeker     ===========================================================
#CircularErrorRadius=0  //20.0               // Circular error radius in meters
#Homing
SeekerGain=0.0                         // Seeker gain in dB
SeekerFOV=90.0                         // Seeker field-of-view in degrees
SeekerActiveRange=0.0
SeekerPassiveRange=20.0                // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
Zoom=3
TargetMemory=True
#ECCM
AntiCountermeasuresBonus=0.4           // This value substracted from probability of spoofing by countermeasures (0...1)
#Search params for torpedoes
#SelfDestruct
SelfDestructAfterTargetGone=False
SelfDestructDelay=5.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/usaf_gbu-15/
ResourcesRoot=usaf_gbu-15
ResourcesMesh=usaf_gbu-15
ResourcesMaterialFolder=weapons/usaf_gbu-15/
ResourcesMaterial=usaf_gbu_15_mat
############################################################
NumberOfSubModels=0

[---------- Effects ----------]
[Particles]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion

InFlightEffect=None

HitDefaultExplosionClass=VeryLargeGroundHitExplosions
HitShipExplosionClass=LargeShipHitExplosion
#HitAirExplosionClass=LargeShipHitExplosion // Played when bomb explodes at water
HitWaterSplashClass=LargeWaterSplashes
HitGroundExplosionClass=VeryLargeGroundHitExplosions

ExplosionOverwaterSplash=effects/splashes/emitters/splash_bomb

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.04291637