#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# AGM-45 Shrike
Type=Missile                           // can be Projectile, Missile, RBU, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW

Mass=178                               // in kg. Used for aircraft
AmmoPoints=356                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
AirLaunched=True                       // For Encyclopedia. Displays launch altitudes

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=SAMImpacts  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=VeryTiny
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = High Explosive
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering
#6 = Fragmentation

[WarheadData]
WarheadType=6
Power=25
ImpactSize=Small                       // Impact size, can be small, medium, large, verylarge
Penetration=Minor                      // can be minor, moderate, heavy, always

[---------- Guidance ----------]
#Guidance Types:
#0 = None
#1 = IR Homing
#2 = Semi-Active Radar Homing
#3 = Active Radar Homing
#4 = Anti-Radiation Homing
#5 = Laser-Homing
#6 = TV-Homing
#7 = Active Sonar Homing
#8 = Passive Sonar Homing
#9 = Wake Homing
[Guidance]
GuidanceType=4
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=3.0         // time in seconds where the missile moves straight on without guiding
TargetRequired=True
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#MaxLoftAngle=20.0                      // Climb angle for initial loft
#MaxLoftAlt=30000                       // Maximum altitude for lofting, apart of number in feet can be: Maintain - maintain altitude that missile had at lofting phase start, Target - go to altitude target had at the moment of the launch, Launcher - go to altitude launch platform had at the moment of the launch,
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=1000.0             // in N. miles. Recommended to set this distance slightly less than the seeker range
#=========================================  Kinematics  ============================================================
ApplyKinematics=True                   // If we should use full kinematics rules. If this is true, we will only use kinematics 
#for acceleration, instead of calculating acceleration time based on the max velocity. MaxVelocity is still used, since missile stalls at 1/4 max velocity or 500 knots, whichever is less
MaxVelocity=1000.0                     // Maximum speed in knots
MaxTurnRate=12.0                       // Maximum turnrate in degrees per second
AccelerationTime=1.25                  // Burn time for initial booster burn
Acceleration=18.3                      // Gs of acceleration in initial burn
SustainerAccelerationTime=20            // Time of sustainer burn. -1 if there is no sustainer burn
SustainerAcceleration=1.43               // Acceleration of sustainer burn. -1 if there is no sustainer
DragCoefficient=-1               // Drag coefficient. 0 for no drag, 1 for default drag, more for more drag. Defaults to -1, where we calculate it based on missile max range
TypicalTargetAlt=0					// Sets the estimated target altitude (in feet) at which the missile will reach maximum firing range. Use 0 if the target is a surface unit. Default: 50000
TypicalFiringAlt=25000				// Sets the estimated firing altitude (in feet) at which the missile will reach maximum firing range. Use 0 for a surface launch missile. Default: 50000
TypicalLaunchVelocity=500				// Sets the estimated firing speed (in knots) at which the missile will reach maximum firing range. Use 0 for a surface launch missile. Default: 1000
VelocityBleed=0.8                      // Missile will eventually slowdown to MaxVelocity*VelocityBleed at the end of its lifetime
MaxFlightTime=90               // How long until missile entirely fails, acts as a hard limit based on batteries, etc. Default: unlimited
TimeLimited=True
#========================================= Launch stats ============================================================
MinLaunchRange=3.0                     // Minimum launch range in nautical miles
MaxLaunchRange=21.5                    // Maximum launch range in nautical miles
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
WobblingStrength=5                   // amplitude of wobbling. Marks that missile performs some wobbling flight
WobblingSpeed=3                      // frequency of wobbling
VerticalWobblingStrength=5                   // amplitude of wobbling. Marks that missile performs some wobbling flight
VerticalWobblingSpeed=5                      // frequency of wobbling
#========================================     Seeker     ===========================================================
#Homing
SeekerGain=5.0                         // Seeker gain in dB
SeekerFOV=60.0                         // Seeker total field-of-view in degrees. I.e SeekerFOV=60 means "+-30" degrees each side
PassiveRadarGuidanceFrequencies=S-Band,C-Band,X-Band    // Frequences Anti-Radiation, HomeOnJam and secondary Passive Radar Guidance weapons can detect
SeekerActiveRange=0                    // Seeker active range in nautical miles. Relevant for  Active Radar Homing, Laser-Homing and Active Sonar Homing (3, 5 and 7)
SeekerPassiveRange=25                  // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Wake Homing (1, 2, 4, 6, 8 and 9)
TargetMemory=True                      // Always locks on preselected target unless spoofed or jammed
#Misc Guidance Properties
#InsDrift=60							   // In degrees per minute of unguided flight. Shifts the weapon's nose by this amount per minute whenever the missile is not being actively guided (RC, Wire, tracking a target with its seeker)
# cass: meant for making missiles drift when they lose their target, blocked for now due to unresolved issues
#ECCM
#Search params for torpedoes
#SelfDestruct

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/usn_agm-45/
ResourcesRoot=usn_agm-45
ResourcesMesh=usn_agm-45
ResourcesMaterial=usn_agm-45_mat
ResourcesMeshForLaunch=usn_agm-45
ResourcesMeshSwitchTime=0.2  // time in seconds after launch to switch from launch mesh to main mesh
Rotation=0,0,45

NumberOfSubModels=0
[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/aam_effect
BoosterEffectPosition=0,0,-0.012

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.012
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=effects/weapons/emitters/missile_sustainer_small_effect
SustainerEffectPosition=0,0,-0.005 
SustainerEffectStartTime=2.0

HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes
ExplosionOverwaterSplash=False

[---------- Colliders ----------]
[Colliders]
#creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0.0096
Rotation=0,0,0
Scale=0.003,0.003,0.042