[General]
# AGM-84D «Harpoon»
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW

Mass=540                               // in kg. Used for aircraft
AmmoPoints=1350                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
SupplyCategory=Harpoon                 // For Supply System. Makes that presence of such category is required for replenishment of this weapon
AirLaunched=True                       // For Encyclopedia. Displays launch altitudes

CIWSDefenceBonus=5                     // Less chance to be intercepted by CIWS because of anti-interception maneuvers
MissileDefenceBonus=0.05                     // Less chance to be intercepted by SAM because of anti-interception maneuvers
#Armored warhead

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard                    // referenced in effects/decals.ini

SaturationValue=1

[SensorData]
#Visual
VisualIdentificationRange=2  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=0.15
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=45
ImpactSize=Medium                      // Impact size, can be small, medium, large, verylarge
Penetration=Always                     // can be minor, moderate, heavy, always

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=3
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=1.0         // time in seconds where the missile moves straight on without guiding
DropDuration=1.0                       // time in seconds where the missile just falls unpropelled
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
SeaSkimmingAlt=50                      // height in feet for sea skimming
SeaSkimmingMaxDescentAngle=45.0        // Dive angle whlie going to sea skimming
SeaSkimmingNoseUp=2.0                  // "nose up" angle in degrees for sea skimming, reflecting the aerodynamics
SeaSkimmingStartDistToTarget=1000      // in N. miles.
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=8.0               // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM must be slightly more than max range
TerminalAlt=7                         // in feet. Weapon will try to get to this altitude at the start of terminal approach
TerminalPopUpDist=1                    // Pop-up distance in miles
TerminalPopUpHeight=1000               // Pop-up height in feet
TerminalPopUpAngle=70                  // Pop-up climb anble in degrees
SelectivePopUp=True                    // If true - pop up works only against submarines and small boats
TerminalVerticalTurnRate=25            // Override of vertical turn rate in terminal (intended for Pop-up)
SupportsBanking=False                  // if the missile will bank when turning
#========================================= Launch stats ============================================================
MaxVelocity=540.0                      // Maximum speed in knots
Acceleration=0.5                       // Acceleration factor
MaxTurnRate=15.0                       // Maximum turnrate in degrees per second
MinLaunchRange=3.5                     // Minimum launch range in nautical miles
MaxLaunchRange=118                     // Maximum launch range in nautical miles
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#Homing
SeekerGain=40.0                        // Seeker gain in dB
SeekerFOV=45,10                        // Seeker active range in nautical miles. Relevant for  Active Radar Homing, Laser-Homing and Active Sonar Homing (3, 5 and 7)
SeekerActiveRange=20.0                 // Seeker active range in nautical miles. Relevant for Semi-Active Radar Homing, Active Radar Homing, Laser-Homing and Active Sonar Homing (2, 3, 5 and 7)
SeekerPassiveRange=20                   // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
SecondaryPassiveRadarGuidanceType=HomeOnJam  //Used with Active or SemiActive radar seeker. Used to detect emitting targets and home on them prior getting active target lock. Supported values: Full for both radar and ECM emissions and HomeOnJam if can home on jammers only
PassiveRadarGuidanceFrequencies=All    // Frequences Anti-Radiation, HomeOnJam and secondary Passive Radar Guidance weapons can detect
Frequency=Ku-Band                      // Active radar seeker frequency, used to determine the jamming efficiency, jammer should support the same band
PeakPower=35.0                         // Active radar seeker output peak power in kW
#Misc Guidance Properties
RangeGate=2							   // 
SizeGate=10						   //
#ECCM
AntiCountermeasuresBonus=0.3          // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.2                   // This value substracted from probability of being jammed  (0...1)
#Search params for torpedoes
#SelfDestruct
SelfDestructDelay=5.0                  // delay in seconds for self destruction
[---------- Mesh definitions----------]
[Models]

ResourcesFolder=weapons/usn_agm-84/
ResourcesRoot=usn_agm-84
ResourcesMesh=usn_agm-84
ResourcesMaterial=usn_agm-84d_mat
############################################################

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=None
InFlightEffect=effects/weapons/emitters/turbojet_sustainer_small
InFlightEffectPosition=0,0,-0.022
InFlightEffectStartTime=3.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes
HitDefaultExplosionClass=MediumMissileExplosions
DebrisTrailClass=MissileDebrisFire
DebrisSplashClass=SmallWaterSplashes

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.06606571
