[General]
# Mk-84 900kg bomb
Type=Bomb                              // can be Projectile, Missile, RBU, ASROC, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW

Mass=925                               // in kg. Used for aircraft
AmmoPoints=925                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=1       // Biggest range in nm at which this unit can be visually identified
IRSignature=VerySmall
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=62
ImpactSize=VeryLarge                // Impact size, can be small, medium, large, verylarge
Penetration=Heavy              // can be minor, moderate, heavy, always

[---------- Guidance ----------]
#Guidance Types:
#0 = None
#1 = IR Homing
#2 = Semi-Active Radar Homing
#3 = Active Radar Homing
#4 = Anti-Radiation Homing
#5 = Laser-Homing
#6 = TV-Homing
#7 = Active Sonar Homing
#8 = Passive Sonar Homing
#9 = Wake Homing
[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=1.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================

#========================================= Launch stats ============================================================
MinLaunchRange=0.01                    // Minimum launch range in nautical miles
MaxLaunchRange=10.0                    // Maximum launch range in nautical miles
MinLaunchAltitude=200                  // Minimum launch altitude in feet.
MaxLaunchAltitude=60000                // Maximum launch altitude in feet.
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
CircularErrorRadius=20.0              // Circular error radius in meters
#Homing
#ECCM
#SelfDestruct
SelfDestructDelay=0.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/usn_bombs/
ResourcesRoot=usn_bombs
ResourcesMesh=usn_mk-84
ResourcesMaterial=usn_mk-82_mat
############################################################
NumberOfSubModels=0
[Particles]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion

InFlightEffect=None

HitDefaultExplosionClass=VeryLargeGroundHitExplosions
HitShipExplosionClass=LargeShipHitExplosion
#HitAirExplosionClass=LargeShipHitExplosion // Played when bomb explodes at water
HitWaterSplashClass=LargeWaterSplashes
HitGroundExplosionClass=VeryLargeGroundHitExplosions

ExplosionOverwaterSplash=effects/splashes/emitters/splash_bomb

[---------- Colliders ----------]
[Colliders]
# creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.04291637