#!/usr/bin/env python3
"""Derive V8 comparisons and complete loadout budgets from shipped data."""
from pathlib import Path
import csv,json
from era_upgrade import ROOT,MOD,ROLES,YEARS,unit_id,read_ini
from investment_programme import BLOCKS

def number(value):
    return f'{value:,.0f}' if abs(value-round(value))<.01 else f'{value:,.1f}'

def table(headers,rows):
    clean=lambda x:str(x).replace('|',' / ').replace('\n',' ')
    return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join(['---']*len(headers))+'|']+['| '+' | '.join(clean(x) for x in row)+' |' for row in rows])+'\n'

def main():
    m=json.loads((ROOT/'loadout_manifest.json').read_text());c=json.loads((ROOT/'weapon_catalog.json').read_text())
    docs=ROOT/'docs';docs.mkdir(exist_ok=True)
    def stores(values):return '; '.join(f'{n} × {c[k]["name"]}' for k,n in values.items()) or 'Empty'
    comparison=[];investment={};csv_rows=[];all_used={k for s in m.values() for ld in s['loadouts'].values() for k in ld['stores']}
    fits={'f':'FleetIntercept / AirToAirLongRange','fb':'AntiShip / AntiShipHeavy / AntiShipLongRange','rf':'ReconFast / ReconLongRange','ef':'EWLongRange / EscortSEAD'}
    for role,v in ROLES.items():
        for year in YEARS:
            uid=unit_id(role,year);s=m[uid]
            comparison.append([f'{s["name"]} {s["nickname"]}',year,s['role'],number(s['empty_mass_kg']),s['mach_limit'],s['cruise_mach'],number(s['nominal_cruise_range_miles']),f"{s['propulsion']['afterburner_thrust_n_per_engine']/1000:.2f}".rstrip('0').rstrip('.'),'M61 / 2,000' if s['gun'] else 'None',len(s['loadouts']),fits[role]])
            investment[uid]={k:s[k] for k in ('name','nickname','edition','empty_mass_components_kg','propulsion','flight_response','nominal_cruise_range_miles','investment_programme')}
    text='# V8: all sixteen aircraft compared\n\nFour original roles, each in four funded editions. Values below come from the shipped configuration and manifests. Empty masses and naval upgrades are estimates. Maximum/cruise Mach values are settings, not verified flight results. Range is the nominal native Miles field, not combat radius.\n\n'
    text+=table(['Aircraft','Year','Role','Empty kg','Max Mach','Cruise Mach','Range miles','AB kN/engine','Gun / rounds','Presets','Suggested fit'],comparison)
    text+='\nRF uses its explicit fictional Mach 3 propulsion package and triple WaterPig velocity/thrust gains for the same year. FB carries the other families\' period weapon types, while F/RF/EF preserve specialised roles. EF always has two physical ECM pods and two offensive systems; FB receives removable offensive ECM only in its EW fits.\n\n'
    text+='The 167 selectable preset names include compatible Default/mission aliases with repeated inventories. Counts by year are 39 / 40 / 42 / 46. Service gates are 1980–1984, 1985–1994, 1995–2002 and 2003–2050. Unsuffixed aircraft IDs select 1980.\n\n[Complete loadouts and weight budgets](../COMPLETE_BREAKDOWN_V8.md) · [Investment details](INVESTMENT_PROGRAMME.md) · [Release notes](../RELEASE_NOTES_V8.md)\n'
    (docs/'AIRCRAFT_COMPARISON.md').write_text(text)
    keys=[('Engine for F/FB/EF','engine'),('Dry thrust N/engine for F/FB/EF','dry_n'),('Afterburning thrust N/engine for F/FB/EF','afterburner_n'),('Velocity/thrust response multiplier','acceleration'),('Pitch/heading/bank gain multiplier','controls'),('Nominal cruise-range factor','range_factor'),('Cruise Mach for F/FB/EF','cruise'),('Climb-setting multiplier','climb_factor'),('Additional systems/control mass kg','systems_mass'),('Propulsion-retrofit allowance kg','engine_mass'),('RF thermal allowance kg','rf_thermal_mass'),('Radar gain addition','radar_gain'),('Radar range factor','radar_range_factor'),('Main radar target channels','radar_targets'),('Main radar weapon channels','radar_weapons'),('Radar look-down multiplier','lookdown'),('FLIR range multiplier','flir'),('RWR/ELINT gain','esm_gain'),('RWR bearing-resolution setting','rwr_resolution'),('ELINT bearing-resolution setting','elint_resolution'),('Defensive ECM JamChance','decm'),('Offensive ECM PeakPower field','jam_power'),('Offensive ECM MaxRange field','jam_range'),('Offensive ECM Gain','jam_gain'),('Offensive ECM channels per system','jam_channels'),('FB weapon ReadyUpTime','ready_fb'),('Other weapon ReadyUpTime','ready_other'),('Weapon CoolDownTime','cooldown')]
    text='# V8 Australian investment programme\n\nEvery edition assumes heavy Australian funding for naval conversion, propulsion, flight controls, weapons integration, targeting and EW. Native settings improve by year. They are hypothetical programme ratings, not measured historical N-family performance.\n\n'
    text+=table(['Setting']+[str(y) for y in YEARS],[[label]+[BLOCKS[y][key] for y in YEARS] for label,key in keys])
    text+='\nThe main radar values above apply to the fleet/strike donor. Separate Phoenix targeting retains six target and six weapon channels. Radar RangeResolution is 30 / 25 / 18 / 12; HasDataLink is False / False / True / True. Offensive ECM has two separate systems, each with the dated channel setting; system count remains two. Native power/range fields are not independently calibrated engineering ratings.\n\n'
    text+='F uses AWG-9 donor geometry/settings, labelled as a hypothetical APG-71-class digital adaptation from 1995. The other roles use APQ-161 native settings to represent naval multimode radar. No new radar/flight simulation engine, interactive digital cockpit or MFD mesh is introduced. The nominal range factor does not guarantee an equivalent increase in combat radius.\n\n'
    text+=table(['RF propulsion setting']+[str(y) for y in YEARS],[[label]+[m[unit_id('rf',y)]['propulsion'][key] for y in YEARS] for label,key in [('Dry N per engine','dry_thrust_n_per_engine'),('Afterburning N per engine','afterburner_thrust_n_per_engine')]])
    text+='\nRF keeps Mach 2.52 cruise and Mach 3 maximum throughout. VelocityGain and ThrustGain stay three times WaterPig\'s matching edition, with the same dated improvement factor. This is not triple maximum airspeed. Use ReconFast, independent orders and appropriate altitude for a sprint; actual AI flight needs runtime testing.\n\n'
    text+='GE\'s historical status report supplies the 120 kN F110-GE-400 and 129 kN F110-GE-129 afterburning classes, available before the assigned editions. F-111 adaptation, installed dry thrust, TF30 uprating, mass allowances, thermal upgrades and control/sensor ratings are estimates. [GE reference](https://www.geaerospace.com/news/press-releases/defense-engines/ge-aircraft-engines-military-engine-status-report). The RF package is entirely fictional.\n\n[Aircraft comparison](AIRCRAFT_COMPARISON.md) · [Full mass/loadout breakdown](../COMPLETE_BREAKDOWN_V8.md)\n'
    (docs/'INVESTMENT_PROGRAMME.md').write_text(text)
    text='# V8 complete aircraft, loadout and mass breakdown\n\nGenerated from the shipped INIs and manifests. All 16 aircraft, all 167 selectable presets and all 61 local store definitions are listed. Compatible aliases may carry identical stores. Values are rounded carried-mass budgets; fictional naval equipment and retrofit allowances are explicit.\n\n'
    text+='## Empty mass components\n\nThe basic reference is 23,300 kg F-111C. The retained fictional bay is not re-engineered. Every version has 14,897 kg internal fuel; tank fuel and M61 ammunition are separate from empty mass.\n\n'
    component_keys=list(next(iter(m.values()))['empty_mass_components_kg'])
    text+=table(['Aircraft','Year','Basic reference kg','Naval kg','Role kg','Gun hardware kg','Edition avionics kg','Systems/controls kg','Propulsion kg','RF thermal kg','Total kg'],[[s['name'],s['edition']]+[number(s['empty_mass_components_kg'][k]) for k in component_keys]+[number(s['empty_mass_kg'])] for s in m.values()])
    text+='\n## Budget rules\n\n- Each 600-US-gallon tank: 1,770 kg fuel plus estimated 150 kg dry shell. Two tanks give 18,437 kg total fuel; four give 21,977 kg.\n- Fixed M61 hardware/feed/housing allowance: 650 kg within F/FB/RF empty mass. Loaded 2,000-round magazine: another 544 kg. EF has no gun.\n- Mk 82 six-bomb racks include one-sixth of an estimated 100 kg rack per bomb.\n- Full-fuel takeoff budget = empty mass + dry stores/rack allowances + internal/external fuel + gun ammunition.\n- Every preset is checked against the 51,845 kg F-111C reference maximum. This is not a carrier catapult/arrestor certification.\n\n'
    for uid,s in m.items():
        text+=f'## {s["name"]} {s["nickname"]} — {s["edition"]}\n\nID: `{uid}`. Role: {s["role"]}. Empty: {number(s["empty_mass_kg"])} kg. Internal fuel: 14,897 kg. Gun ammunition: {"544 kg / 2,000 rounds" if s["gun"] else "none"}. Max Mach: {s["mach_limit"]}; cruise Mach: {s["cruise_mach"]}.\n\n'
        rows=[]
        for preset,ld in s['loadouts'].items():
            external=ld['auxiliary_external_stores'];bay=ld['internal_bay_stores']
            rows.append([preset,stores(ld['wing_stores']),stores(external),stores(bay),number(ld['stores_mass_kg']),number(ld['total_fuel_kg']),number(ld['full_fuel_takeoff_mass_kg']),number(ld['margin_kg'])])
            csv_rows.append(dict(aircraft_id=uid,model=s['name'],nickname=s['nickname'],edition=s['edition'],role=s['role'],preset=preset,wing_stores=stores(ld['wing_stores']),auxiliary_external_stores=stores(external),internal_bay_stores=stores(bay),empty_mass_kg=s['empty_mass_kg'],stores_mass_kg=ld['stores_mass_kg'],total_fuel_kg=ld['total_fuel_kg'],gun_ammunition_mass_kg=ld['gun_ammunition_mass_kg'],full_fuel_takeoff_mass_kg=ld['full_fuel_takeoff_mass_kg'],reference_max_takeoff_kg=ld['reference_max_takeoff_kg'],margin_kg=ld['margin_kg']))
        text+=table(['Preset','Wing stores','Auxiliary external','Internal bay','Dry stores kg','Total fuel kg','Takeoff kg','Margin kg'],rows)+'\n'
    text+='## Every local store definition\n\nDated aliases use the same physical store geometry and mass with year-specific sensors. Unselected legacy definitions are retained for compatibility; 61 definitions do not mean 61 different weapon designs. Tank shell mass excludes fuel.\n\n'
    text+=table(['ID','Name','Mass kg','Fuel kg','Earliest edition','Used in presets','Simulation/geometry notes'],[[k,v['name'],number(v['mass_kg']),v.get('fuel_kg',0),v['earliest_edition'],'Yes' if k in all_used else 'Compatibility definition',v.get('simulation','')] for k,v in c.items()])
    text+='\n## Preserved design and simulation limits\n\nMudPig AntiShip is two wing Harpoons/two IR missiles with empty bay; AntiShipHeavy is four wing and three bay Harpoons; AntiShipLongRange is two wing and three bay Harpoons, two IR missiles and two tanks. Bay stations, concealment and doors are exact original definitions. The separately relocated M61 is fictional; no new gun fairing is drawn.\n\nEF retains two physical pylon ECM pods and two offensive sensors. FB only carries removable offensive containers in its EW presets. Designation and EO control pods occupy counted external stations. Existing cockpit, model and landing animation geometry remains.\n\nNative modern-weapon approximations: AMRAAM lacks platform midcourse correction; ASRAAM lacks helmet sight/LOAL; EO weapons lack manual man-in-the-loop retargeting; Block II Harpoon models radar-homing ship attack; JDAM/JSOW use CEP/ballistic/glide settings instead of full GPS/INS. Period choices assume funded Australian integration, including accelerated early procurement.\n\nStatic checks do not prove gun fire, release trajectories, AI Mach 3 behaviour, ECM display, date filtering or carrier landings. These still need Sea Power runtime testing. [References](HISTORICAL_REFERENCES.md) · [Aircraft comparison](docs/AIRCRAFT_COMPARISON.md) · [Investment](docs/INVESTMENT_PROGRAMME.md)\n'
    (ROOT/'COMPLETE_BREAKDOWN_V8.md').write_text(text)
    with (ROOT/'ALL_LOADOUTS_V8.csv').open('w',newline='') as f:
        writer=csv.DictWriter(f,fieldnames=list(csv_rows[0]));writer.writeheader();writer.writerows(csv_rows)
    (ROOT/'investment_manifest.json').write_text(json.dumps(investment,indent=2)+'\n')
    reports={name:json.loads((ROOT/name).read_text()) for name in ('VALIDATION.json','CARRIER_VALIDATION.json','USN_TEXTURE_VALIDATION.json')}
    heaviest=max((ld['full_fuel_takeoff_mass_kg'],uid,preset,ld['margin_kg']) for uid,s in m.items() for preset,ld in s['loadouts'].items())
    text='# V8 release notes\n\nFresh remake from the saved V6 base: sixteen aircraft, 167 selectable presets, dated Australian investment and eight USN-inspired late liveries. Original role/model/bay/landing contracts and M61/ECM/carrier arrangements are retained. Native modern-weapon approximations and explicit hypothetical naval masses remain documented.\n\n'
    text+=table(['Verification','Status','Checks/maps'],[[name,r['status'],r.get('checks',len(r.get('maps',[])))] for name,r in reports.items()])
    text+=f'\nHeaviest full-fuel budget: {heaviest[1]} / {heaviest[2]} at {number(heaviest[0])} kg, margin {number(heaviest[3])} kg. Python compilation and installer shell syntax are checked separately. ZIP integrity and SHA-256 are supplied with the package.\n\n'
    text+='Carrier validation uses native and representative RAN/custom deck fixtures, not the user\'s exact installed RAN carriers. Installation checks cover staging, backups, source preservation and idempotence. Preview images render the shipped assets and omit stock weapon meshes unavailable outside the game.\n\n**Runtime tested: no.** Sea Power is not installed here. Actual gun fire, guidance/release, date filtering, Mach 3 flight, ECM display and landings require in-game verification. No new DLL, interactive cockpit, real GPS weapon simulation or real carrier certification is claimed.\n\nThe README, all-aircraft/system comparisons, every loadout/mass breakdown, CSV/JSON data, references, Steam description, credits, authoring sources and validation reports are included. GitHub publication is separate from this downloadable release.\n'
    (ROOT/'RELEASE_NOTES_V8.md').write_text(text)
    print(json.dumps({'aircraft_comparison_rows':len(comparison),'loadout_rows':len(csv_rows),'local_store_definitions':len(c),'documents_generated':6}))
if __name__=='__main__':main()
